-- MySQL Script generated by MySQL Workbench
-- Mon Dec  3 13:39:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema task_managment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_managment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_managment` DEFAULT CHARACTER SET latin1 ;
USE `task_managment` ;

-- -----------------------------------------------------
-- Table `task_managment`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_managment`.`jobs` (
  `job_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`job_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `task_managment`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_managment`.`workers` (
  `worker_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `user_name` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `job` INT(11) NULL DEFAULT NULL,
  `manager` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`worker_id`),
  UNIQUE INDEX `user_name` (`user_name` ASC) VISIBLE,
  INDEX `fk_job` (`job` ASC) VISIBLE,
  INDEX `fk_manager` (`manager` ASC) VISIBLE,
  CONSTRAINT `fk_job`
    FOREIGN KEY (`job`)
    REFERENCES `task_managment`.`jobs` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manager`
    FOREIGN KEY (`manager`)
    REFERENCES `task_managment`.`workers` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `task_managment`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_managment`.`projects` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `customer` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `team_leader` INT(11) NOT NULL,
  `develop_houres` INT(11) NOT NULL,
  `qa_houres` INT(11) NOT NULL,
  `ui_ux_houres` INT(11) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  INDEX `fk_team_leader` (`team_leader` ASC) VISIBLE,
  CONSTRAINT `fk_team_leader`
    FOREIGN KEY (`team_leader`)
    REFERENCES `task_managment`.`workers` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `task_managment`.`project_workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_managment`.`project_workers` (
  `project_worker_id` INT(11) NOT NULL AUTO_INCREMENT,
  `worker_id` INT(11) NOT NULL,
  `project_id` INT(11) NOT NULL,
  `allocated_hours` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`project_worker_id`),
  INDEX `fk_worker` (`worker_id` ASC) VISIBLE,
  INDEX `fk_project` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `task_managment`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_worker`
    FOREIGN KEY (`worker_id`)
    REFERENCES `task_managment`.`workers` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `task_managment`.`work_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_managment`.`work_hours` (
  `work_hours_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_work_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `start` TIME NULL DEFAULT NULL,
  `end` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`work_hours_id`),
  INDEX `fk_project_worker` (`project_work_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_worker`
    FOREIGN KEY (`project_work_id`)
    REFERENCES `task_managment`.`project_workers` (`project_worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
